data:
  vr_model_dir: pretrained_vr/model.pt
  f0_extractor: 'parselmouth' # 'parselmouth' (singing) or 'dio' (speech) or 'harvest' (speech)
  f0_min: 65 # about C2
  f0_max: 800 # about G5
  sampling_rate: 44100
  n_fft: 2048
  win_length: 2048
  block_size: 512 # Equal to hop_length
  n_mels: 128
  mel_fmin: 40 
  mel_fmax: 16000 # <= sampling_rate / 2 
  duration: 2 # Audio duration during training, must be less than the duration of the shortest audio clip
  train_path: data/train # Create a folder named "audio" under this path and put the audio clip in it
  valid_path: data/val # Create a folder named "audio" under this path and put the audio clip in it
model:
  type: 'CombSub'
  win_length: 2048
  use_mean_filter: true  
  n_mag_harmonic: 512
  n_mag_noise: 256
loss:
  fft_min: 256
  fft_max: 2048
  n_scale: 4 # rss kernel numbers
  lambda_uv: 1.0 # uv regularization
  uv_tolerance: 0.05 # set it to a large value or try other f0 extractors if val_loss_uv is much higher than train_loss_uv
  detach_uv_step: 2000
device: cuda
env:
  expdir: exp/combsub-test
  gpu_id: 0
train:
  num_workers: 2 # if your cpu and gpu are both very strong, set to 0 may be faster!
  batch_size: 24
  cache_all_data: true # Save Internal-Memory if it is false, but may be slow
  epochs: 100000
  interval_log: 10
  interval_val: 2000
  lr: 0.0005
  weight_decay: 0
  save_opt: false